import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import Footer from "@/components/Footer";
import "./globals.css";
import Transition from "@/components/Transition";
import Template from "./template";

export const metadata: Metadata = {
  title: "Amprio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SpeedInsights />
        <Template>
          <div className="min-h-[100vh]">{children}</div>
          <Footer />
        </Template>
      </body>
    </html>
  );
}
