import { SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next";

import Footer from "@/components/Footer";
import Layout from "@/components/Layout";
import Template from "./template";

import "./globals.css";
import ReactQueryProvider from "@/components/ReactQueryProvider";
import { AppSidebar } from "@/components/app-sidebar";
import Nav from "@/components/Navbar/Nav";
import { getCookie } from "@/components/Backend";
import WhatsApp from "@/components/WhatsApp";

export const metadata: Metadata = {
  title: "Amprio",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Caveat&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="overflow-x-hidden">
        <SpeedInsights />
        <Template>
          <ReactQueryProvider>
            {/*React-query context wrapper */}
            <SidebarProvider defaultOpen={false}>
              <AppSidebar />
              <Layout cookie={getCookie()}>
                <Nav />
                {/*custom context hook wrapper + contains sidebar*/}
                <div className="min-h-[100vh] w-[100vw]">
                  {children}
                  <WhatsApp />
                </div>
                <Footer />
              </Layout>
            </SidebarProvider>
          </ReactQueryProvider>
        </Template>
      </body>
    </html>
  );
}
